export const routes = {
  Home: 'home',
  SignIn: 'sign-in',
  TabNavigation: 'tab-navigation',
  AppointmentsMain: 'appointments-main',
  Insurance: 'insurance',
  Notifications: 'notifications',
  Profile: 'profile',
  CreateAppointment: 'create-appointment',
  MedBotChat: 'med-bot-chat',
  OtpVerification: 'otp-verification',
  CreateUser: 'create-user',
  Compensation: 'compensation',
  CompensationRequest: 'compensation-request',
  CompensationOtpVerification: 'compensation-otp-verification',
  CompensationsHistory: 'compensations-history',
  InsuranceDetails: 'insurance-details',
  InsuranceCertificate: 'insurance-certificate',
  InsuranceMedicalNetwork: 'insurance-medical-network',
  InsuranceElectronicReferrals: 'insurance-electronic-referrals',
  InsuranceDocument: 'insurance-document',
  InsuranceSupport: 'insurance-support',
} as const;
