export const routes = {
  Home: 'home',
  SignIn: 'sign-in',
  TabNavigation: 'tab-navigation',
  AppointmentsMain: 'appointments-main',
  AppointmentDetails: 'appointment-details',
  Insurance: 'insurance',
  Notifications: 'notifications',
  Profile: 'profile',
  CreateAppointment: 'create-appointment',
  MedbotChat: 'medbot-chat',
  OtpVerification: 'otp-verification',
  CreateUser: 'create-user',
  Compensation: 'compensation',
  CompensationRequest: 'compensation-request',
  CompensationOtpVerification: 'compensation-otp-verification',
  CompensationsHistory: 'compensations-history',
  InsuranceDetails: 'insurance-details',
  MedicalNetwork: 'medical-network',
  ElectronicReferrals: 'electronic-referrals',
  InsuranceSupport: 'insurance-support',
  DocumentViewer: 'document-viewer',
} as const;
